spring:
    data:
      web:
          pageable:
              default-page-size: 10
              max-page-size: 2000
    datasource:
        url: jdbc:h2:tcp://localhost:9092/~/datajpa  # ? ?? ??
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                #show_sql:


logging:
    level:
        org.hibernate.SQL: debug
